---
version: "2.4"

services:
  nullptr:
    hostname: ${INSTANCE}_nullptr
    runtime: runc
    privileged: false
    image: internal-registry.allesctf.net/allesctf20/nullptr
    networks:
      ctf:
        ipv4_address: ${PREFIX}.10

networks:
  ctf:
    driver: bridge
    internal: true
    external: no
    ipam:
      driver: default
      config:
        - subnet: ${PREFIX}.0/24
