version: "2.4"

services:
  olddos:
    hostname: ${INSTANCE}_olddos
    runtime: kataprivileged
    privileged: true
    image: internal-registry.allesctf.net/allesctf20/olddos
    networks:
      ctf:
        ipv4_address: ${PREFIX}.10

networks:
  ctf:
    driver: bridge
    internal: true
    external: no
    ipam:
      driver: default
      config:
        - subnet: ${PREFIX}.0/24

