version: '3'
services:
  maria:
    build:
      context: ./maria
    hostname: hax1_wimc_maria
    environment:
      - MYSQL_ROOT_PASSWORD=IpBAu6da3fJDTu6ts8ExNdfHN5HCl4Xu
      - "FLAG=ALLES{th4nks f0r y0uR h31p, my fr13nd!}"
    privileged: false
    restart: always
    networks:
      - ctf
  api:
    build:
      context: ./api
    hostname: wimc_api
    depends_on:
      - maria
    ports:
      - "127.0.0.1:10001:1337"
    privileged: false
    restart: always
    environment:
      - MYSQL_HOST=maria
    networks:
      - ctf
  app:
    build:
      context: ./app
    hostname: wimc_app
    depends_on:
      - api
    ports:
      - "127.0.0.1:10002:1337"
    privileged: false
    networks:
      - ctf

  admin:
    build:
      context: ./admin
    hostname: wimc_admin
    depends_on:
      - maria
    ports:
      - "127.0.0.1:10003:1337"
    privileged: false
    restart: always
    environment:
      - MYSQL_HOST=maria
    networks:
      - ctf
networks:
  ctf:
    driver: bridge
