language: python
sudo: false
cache: pip
python:
  - "2.7"
env:
  - VCR_RECORD_MODE=none  # only use recorded tests, errors on nonexisting tests
#  - VCR_RECORD_MODE=all   # don't use recorded tests, do it LIVE

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - pip install coverage coveralls
install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt

before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)
# run tests with test coverage
script: coverage run --source pyfibot -m py.test

# upload coverage results to coveralls.io
after_success:
  - coveralls
notifications:
  irc:
    channels:
      - "irc.nerv.fi#pyfibot"
    skip_join: true

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/df5efda3d60663454d00  # gitter notification
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
