version: '3.7'

services:
  nginx:
    image: nginx:alpine
    restart: always
    networks:
      - external
      - internal
    ports:
      - "1337:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"    

  app:
    build: ./app/
    restart: always
    networks:
      - internal

networks:
  external:
  internal:
    internal: true
