version: "2.4"

services:
  can-over-ip:
    hostname: ${INSTANCE}_socketcandy
    runtime: kataprivileged
    privileged: false
    image: internal-registry.allesctf.net/allesctf20/socketcandy
    cap_add:
      - NET_ADMIN
    networks:
      ctf:
        ipv4_address: ${PREFIX}.10

networks:
  ctf:
    driver: bridge
    internal: true
    external: no
    ipam:
      driver: default
      config:
        - subnet: ${PREFIX}.0/24

