listeners:
- query_port: 25565
  motd: 'ALLES! Craft'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1337
  tab_size: 60
  force_default_server: true
  forced_hosts:
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  admin:
  - bungeecord.command.list
  - bungeecord.command.server
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: 96bd6935-63c9-476d-985f-bffe9b8aac10
player_limit: -1
ip_forward: true
groups:
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: true
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: 'ALLES! Craft'
    address: lobby:31337
    restricted: false
